[package]
name = "blewis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
bitreader = "0.3.8"
bytes = "1.5.0"
ordered-float = "4.2.0"
